matrix:
    include:
        - language: python
            python: 3.6
            before_script:
                - cd tests
            script:
                - python -m unittest discover

        - language: python
            python: 2.7
            before_script:
                - cd tests
            script:
                - python -m unittest discover

        - language: node_js
            node_js:
                - "7"
                - "6"
                - "5"
            script:
                - npm run lin
                - npm run test:cov
            after_success:
                - npm run coverage
            cache:
                npm: true
                directories:
                    - node_modules

notifications:
    email:
        recipients:
            - 265815F@curtin.edu.au
        on_success: never
        on_failure: always
